name: Publish to NPM

on:
  push:
    branches:
      - main           # Pubblica su ogni push su 'main'
    tags:
      - 'v*'           # Pubblica se un tag con formato 'v1.0.0' viene creato

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Puoi scegliere la versione di Node.js che preferisci
          registry-url: 'https://registry.npmjs.org'  # URL del registro NPM

      - name: Build the project
        run: npm run build  # Aggiungi il comando per costruire il progetto se necessario

      - name: Publish package to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public  # Usa 'public' per pacchetti pubblici, 'restricted' per pacchetti privati
